### ISSUE TITLE
Markup Errors When Running A Second Time From CLI

### ISSUE THREAD

**Issue by edolyne** [NewSpring/norma-markup#2]
After running markup for a second time from the CLI this error generates:

markup
Ø Running markup
Ø Markup: ✔ All done!
Ø markup
Ø Running markup
Ø Markup: ✔ All done!
Ø Error running task sequence: { task: 'markup',
  duration: 0.000308413,
  hrDuration: [ 0, 308413 ],
  message: 'markup catch',
  err: [TypeError: Object html has no method 'join'] }
Object html has no method 'join'TypeError: Object html has no method 'join'
  at Gulp.<anonymous> (/Users/ed.long/Sites/edolyne.com/node_modules/norma-markup/package.coffee:71:30)
  at module.exports (/Users/ed.long/Sites/edolyne.com/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/ed.long/Sites/edolyne.com/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/ed.long/Sites/edolyne.com/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/ed.long/Sites/edolyne.com/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at runNextSet (/Users/ed.long/Sites/edolyne.com/node_modules/norma-markup/node_modules/run-sequence/index.js:74:16)
  at runSequence (/Users/ed.long/Sites/edolyne.com/node_modules/norma-markup/node_modules/run-sequence/index.js:85:2)
  at Gulp.<anonymous> (/Users/ed.long/Sites/edolyne.com/node_modules/norma-markup/package.coffee:112:7)
  at module.exports (/usr/local/lib/node_modules/normajs/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/usr/local/lib/node_modules/normajs/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/usr/local/lib/node_modules/normajs/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/usr/local/lib/node_modules/normajs/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at runNextSet (/usr/local/lib/node_modules/normajs/node_modules/run-sequence/index.js:64:16)
  at runSequence (/usr/local/lib/node_modules/normajs/node_modules/run-sequence/index.js:75:2)
  at runTask (/usr/local/lib/node_modules/normajs/lib/methods/watch.coffee:32:5)
  at /usr/local/lib/node_modules/normajs/lib/methods/watch.coffee:105:9
  at Interface.<anonymous> (/usr/local/lib/node_modules/normajs/lib/utilities/prompt.coffee:121:5)
  at Interface.EventEmitter.emit (events.js:117:20)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.EventEmitter.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.EventEmitter.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:745:14)
  at ReadStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:407:10)
  at emitReadable (_stream_readable.js:403:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)

Ø

**Comment by edolyne** [comment]
This error is now showing each time you run markup from the cli
